"""empty message

Revision ID: 2e40c0799488
Revises: 
Create Date: 2021-02-07 23:55:33.785216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e40c0799488'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.String(length=250), nullable=False),
    sa.Column('nameRu', sa.String(length=250), nullable=False),
    sa.Column('nameEn', sa.String(length=250), nullable=False),
    sa.Column('kinopoiskUrl', sa.String(length=250), nullable=False),
    sa.Column('posterUrl', sa.String(length=250), nullable=False),
    sa.Column('year', sa.String(length=250), nullable=False),
    sa.Column('filmLength', sa.String(length=250), nullable=False),
    sa.Column('countries', sa.String(length=250), nullable=False),
    sa.Column('genres', sa.String(length=250), nullable=False),
    sa.Column('type', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_list')
    # ### end Alembic commands ###
