"""empty message

Revision ID: 678724fa9e76
Revises: 2e40c0799488
Create Date: 2021-02-14 23:41:36.397836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '678724fa9e76'
down_revision = '2e40c0799488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film_list', sa.Column('imdb_rating', sa.String(length=250), nullable=False))
    op.add_column('film_list', sa.Column('kp_rating', sa.String(length=250), nullable=False))
    op.alter_column('film_list', 'countries',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('film_list', 'filmLength',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('film_list', 'film_id',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('film_list', 'genres',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('film_list', 'kinopoiskUrl',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)

    op.alter_column('film_list', 'nameEn',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('film_list', 'nameRu',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('film_list', 'posterUrl',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('film_list', 'type',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('film_list', 'year',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('film_list', 'year',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('film_list', 'type',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('film_list', 'posterUrl',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('film_list', 'nameRu',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('film_list', 'nameEn',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('film_list', 'kinopoiskUrl',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('film_list', 'genres',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('film_list', 'film_id',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('film_list', 'filmLength',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('film_list', 'countries',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
